export const Svg = {
  ICProgramOfIntrest: require('./svg/program_of_intrest.svg'),
}

export const Icons = {
  IcUser: require('./icons/user.png'),
  IcAnalytics: require('./icons/analytics.png'),
  IcConversation: require('./icons/conversation.png'),
  IcScheduleFilled: require('./icons/scheduleFilled.png'),
  IcTimesheet: require('./icons/timesheet.png'),
  IcHamburger: require('./icons/hamburger.png'),
  IcLogo: require('./icons/logo.png'),
  IcSupportIcon: require('./icons/supportIcon.png'),
  IcCalendar: require('./icons/calendar1.png'),
  IcTime: require('./icons/time.png'),
  IcPreviousCal: require('./icons/previousCal.png'),
  IcNextCal: require('./icons/nextCal.jpg'),
  IcCross: require('./icons/cross.png'),
  IcEyeClose: require('./icons/eyeclose.png'),
  IcEyeOpen: require('./icons/Eye.png'),
  IcRememberbox: require('./icons/remembarbox.png'),
  IcRememberboxFilled: require('./icons/rememberboxfilled.png'),
  IcNotification: require('./icons/notification.png'),
  IcSearch: require('./icons/search.png'),
  IcBackBtn: require('./icons/backbtn.png'),
  IcPlus: require('./icons/plus.png'),
  IcGoogle: require('./icons/google.png'),
  IcAmbassador: require('./icons/ambassador.png'),
  IcFilter: require('./icons/filter.png'),
  IcSpecification: require('./icons/specification.png'),
  IcLocation: require('./icons/location.png'),
  IcLanguage: require('./icons/language.png'),
  IcShare: require('./icons/share.png'),
  IcIbutton: require('./icons/ibutton.png'),
  IcMajor: require('./icons/major.png'),
  IcLogout: require('./icons/logout.png'),
  IcRight: require('./icons/right.png'),
  IcEdit: require('./icons/edit.png'),
  IcSchedule: require('./icons/schedule.png'),
  IcPdf: require('./icons/pdficon.png'),
  IcChatUnread: require('./icons/chatUnread.png'),
  IcTimer: require('./icons/timer.png'),
  IcBlockedUser: require('./icons/bloackedUser.png'),
  IcNotes: require('./icons/Notes.png'),
  IcBlankNotes: require('./icons/blankNotes.png'),
  IcMessage: require('./icons/messageIcon.png'),
  IcInfo:require('./icons/Info.png'),
  IcCrossLogout:require('./icons/crossbtn.png'),  
  IcThreeDot:require('./icons/threedot.png'),
  IcCamera:require('./icons/camera.png'),
  IcPin:require('./icons/pin.png'),
}

export const Images = {
  indianFlag: require('./images/indianFlag.png'),
  girlImage: require('./images/girlImage.png'),
  logo: require('./images/truleaguelogo.png'),
  regislogo: require('./images/regislogo.png'),
  handshak: require('./images/handshak.png'),
  truleaguelogo: require('./images/truleaguelogo.png'),
  regis: require('./images/regis.png'),
  wellesley: require('./images/wellesley.png'),
  babson: require('./images/babson.png'),
  house: require('./images/house.png'),
  pic1: require('./images/pic1.png'),
  pic2: require('./images/pic2.png'),
  emptyscheduler: require('./images/emptyscheduler.png'),
  networkissue: require('./images/networkissue.png'),
  pic3: require('./images/pic3.png'),
  emptychat: require('./images/emptychat.png'),
  emptymedia: require('./images/emptymedia.png'),
  no_profile_pic: require('./images/no-profile-picture-icon.png')
}